# Generated by Django 3.1.1 on 2020-09-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_filecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='filecontent',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='age',
            field=models.IntegerField(verbose_name='Patient age'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_afternoon_pulse',
            field=models.IntegerField(verbose_name='Average afternoon pulse'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_afternoon_temp',
            field=models.FloatField(verbose_name='Average afternoon temperature in centigrades'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_artificial_light',
            field=models.IntegerField(verbose_name='Average hours under artificial blue light'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_dias_bp',
            field=models.IntegerField(verbose_name='Average diastolic blood pressure'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_sleep_hours',
            field=models.FloatField(verbose_name='Average hours of sleep per night'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_sleep_quality',
            field=models.CharField(choices=[('B', 'Bad'), ('R', 'Regular'), ('G', 'Good')], max_length=1, verbose_name='How patient feels after sleeping'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_sys_bp',
            field=models.IntegerField(verbose_name='Average systolic blood pressure'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_waking_pulse',
            field=models.IntegerField(verbose_name='Average waking pulse'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_waking_temp',
            field=models.FloatField(verbose_name='Average waking temperature in centigrades'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='bodyfat',
            field=models.FloatField(verbose_name='Body fat percentage'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City of residence'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='country',
            field=models.CharField(max_length=64, verbose_name='Country of residence'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='current_medications',
            field=models.TextField(verbose_name='Current drugs or medications'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='current_symptoms',
            field=models.TextField(verbose_name='Current Symptoms'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='family_history',
            field=models.TextField(verbose_name='Family diagnosed conditions'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='height',
            field=models.IntegerField(verbose_name='Height in cm'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='previous_conditions',
            field=models.TextField(verbose_name='Previous diagnosed conditions'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='stresslevel',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1, verbose_name='How stressed the patient feels'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='weight',
            field=models.IntegerField(verbose_name='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='workhours',
            field=models.IntegerField(verbose_name='How many hours does the patient regularly work per day'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='filecontent',
            field=models.FileField(upload_to='media/uploads/', verbose_name='File'),
        ),
    ]
