# Generated by Django 3.1.1 on 2020-09-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_auto_20200917_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='bowelmovements',
            field=models.CharField(choices=[('<1', 'Less than one'), ('1', 'Once'), ('2', 'Twice'), ('3', 'Thrice'), ('>3', 'More than thrice')], default='1', max_length=2, verbose_name='Average bowel movements per day'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='avg_sleep_quality',
            field=models.CharField(choices=[('B', 'Bad'), ('R', 'Regular'), ('G', 'Good')], max_length=1, verbose_name='Energy level after sleeping'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='stresslevel',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1, verbose_name='Level of daily stress'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='workhours',
            field=models.IntegerField(verbose_name='Work hours per day'),
        ),
    ]
