# Generated by Django 3.1.1 on 2020-09-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_auto_20200917_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='current_medications',
            field=models.TextField(default='None', verbose_name='Current drugs or medications'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='current_symptoms',
            field=models.TextField(default='None', verbose_name='Current Symptoms'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='family_history',
            field=models.TextField(default='None', verbose_name='Family diagnosed conditions'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='previous_conditions',
            field=models.TextField(default='None', verbose_name='Previous diagnosed conditions'),
        ),
    ]
