# Generated by Django 3.1.1 on 2020-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_auto_20200917_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
