# Generated by Django 3.1.1 on 2020-09-20 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0007_asignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='requester',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='current_medications',
            field=models.TextField(blank=True, verbose_name='Current drugs or medications'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='family_history',
            field=models.TextField(blank=True, verbose_name='Family diagnosed conditions'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='previous_conditions',
            field=models.TextField(blank=True, verbose_name='Previous diagnosed conditions'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Patient sex'),
        ),
    ]
