# Generated by Django 3.1.1 on 2020-09-20 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0008_auto_20200920_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignee',
        ),
        migrations.AddField(
            model_name='consultation',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_assigned', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
