# Generated by Django 3.1.1 on 2020-09-21 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0009_auto_20200920_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='current_symptoms',
            field=models.TextField(blank=True, verbose_name='Current Symptoms'),
        ),
    ]
