# Generated by Django 3.1.1 on 2020-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='filecontent',
            field=models.FileField(upload_to='uploads/', verbose_name='File'),
        ),
    ]
