# Generated by Django 3.1.1 on 2020-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_auto_20200929_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='alcohol_use',
            field=models.TextField(blank=True, verbose_name='Alcohol Consumption'),
        ),
    ]
